// All inline styles of the main screen, per theme (see makeStyles).
import { COLORS } from "./constants.js";

export function makeStyles(dark) {
  const T = dark
    ? {
        cardBg: "rgba(20,22,18,0)",
        cardBgFrosted: "rgba(20,22,18,0.18)",
        cardBorder: "rgba(255,255,255,0.20)",
        text: "#FDF6E3",
        sub: "#E3D9BC",
        // Text for solid/opaque surfaces (modals, inputs) — same as the
        // regular text here since those surfaces are already dark.
        solidText: "#FDF6E3",
        solidSub: "#E3D9BC",
        inputBg: "rgba(255,255,255,0.06)",
        inputBorder: "rgba(255,255,255,0.20)",
        chipBg: "rgba(255,255,255,0.08)",
        chipBorder: "rgba(255,255,255,0.20)",
        navBg: "#181A15",
        navText: "#F1E9D2",
        headerBg: "rgba(10,20,15,0.22)",
        tableBorder: "rgba(255,255,255,0.18)",
        rowBorder: "rgba(255,255,255,0.08)",
        modalBg: "#1C1D18",
        // Lighter "chalk" blue — the plain one vanishes on the black room.
        pickText: "#9CC8E8",
        pickBorder: "rgba(156,200,232,0.75)",
        pickActiveBg: "#4F86AE",
        pickActiveText: "#fff",
      }
    : {
        cardBg: "rgba(255,251,242,0)",
        cardBgFrosted: "rgba(255,251,242,0.26)",
        cardBorder: "rgba(205,187,144,0.85)",
        // Cards are just blurred (no tint) over the same dark, moody photo
        // as dark theme, so on-photo text needs to be light here too —
        // dark ink only reads on genuinely pale/opaque surfaces (below).
        text: "#FDF6E3",
        sub: "#E3D9BC",
        solidText: COLORS.ink,
        solidSub: "#6E6248",
        inputBg: "rgba(251,247,238,0.55)",
        inputBorder: "#D8CBA9",
        chipBg: "rgba(239,230,204,0.55)",
        chipBorder: "#DCC98F",
        navBg: "rgba(246,240,226,0.12)",
        navText: COLORS.wood,
        headerBg: "rgba(10,20,15,0.16)",
        tableBorder: COLORS.wood,
        rowBorder: "#EEE3C8",
        modalBg: "#FFFDF8",
        // Selectable chips/outline buttons sit right on the dark photo too,
        // so the blue "chalk" accent disappears there — use warm gold.
        pickText: "#F6D48A",
        pickBorder: "rgba(246,212,138,0.8)",
        pickActiveBg: "#E0B35E",
        pickActiveText: "#2A1D0A",
      };

  return {
    outerBg: { position: "fixed", inset: 0, zIndex: 0, overflow: "hidden" },
    outerOverlay: {
      position: "absolute",
      inset: 0,
      background: "transparent",
      transition: "background 0.5s ease",
    },
    page: {
      position: "relative",
      zIndex: 1,
      minHeight: "100vh",
      fontFamily: "'Inter', sans-serif",
      color: T.text,
      paddingBottom: "calc(84px + env(safe-area-inset-bottom))",
      // Inherited by all text below. Light theme is blurred (has a frosted
      // pedestal behind text, so a light shadow is enough); dark theme is
      // fully transparent with no blur backing it, so it leans on a much
      // stronger shadow to stay legible over the photo on its own.
      textShadow: dark ? "0 1px 4px rgba(0,0,0,0.85), 0 2px 12px rgba(0,0,0,0.55)" : "0 1px 3px rgba(0,0,0,0.30)",
    },
    header: {
      padding: "calc(16px + env(safe-area-inset-top)) 20px 18px",
      textAlign: "center",
      background: "radial-gradient(ellipse 70% 120% at 50% 35%, rgba(4,12,8,0.5) 0%, rgba(4,12,8,0.0) 72%)",
    },
    offlineBanner: {
      position: "relative",
      zIndex: 5,
      margin: "calc(8px + env(safe-area-inset-top)) 16px 0",
      padding: "8px 12px",
      borderRadius: "10px",
      background: "rgba(181,71,58,0.85)",
      color: "#FBEFE9",
      fontSize: "12px",
      fontWeight: 600,
      textAlign: "center",
    },
    gameTypeSwitch: {
      display: "inline-flex",
      marginTop: "10px",
      padding: "3px",
      borderRadius: "999px",
      background: "rgba(10,10,8,0)",
      border: "1px solid rgba(255,255,255,0.28)",
      backdropFilter: dark ? "none" : "blur(20px) saturate(160%)",
      WebkitBackdropFilter: dark ? "none" : "blur(20px) saturate(160%)",
    },
    gameTypeSwitchBtn: {
      display: "inline-flex",
      alignItems: "center",
      gap: "6px",
      padding: "6px 15px",
      borderRadius: "999px",
      border: "none",
      background: "transparent",
      color: "rgba(241,233,210,0.65)",
      fontSize: "11.5px",
      fontWeight: 700,
      letterSpacing: "0.3px",
      cursor: "pointer",
      transition: "background 0.25s ease, color 0.2s ease, box-shadow 0.25s ease",
    },
    gameTypeSwitchBtnActive: {
      background: "linear-gradient(135deg, #D9A354 0%, #A9701F 100%)",
      color: "#241705",
    },
    bottomNav: {
      position: "fixed",
      left: 0,
      right: 0,
      bottom: 0,
      zIndex: 20,
      display: "flex",
      gap: "2px",
      padding: "8px 8px calc(8px + env(safe-area-inset-bottom))",
      background: T.navBg,
      backdropFilter: dark ? "none" : "blur(24px) saturate(170%)",
      WebkitBackdropFilter: dark ? "none" : "blur(24px) saturate(170%)",
      borderTop: `1px solid ${T.cardBorder}`,
    },
    bottomNavBtn: {
      flex: 1,
      display: "flex",
      flexDirection: "column",
      alignItems: "center",
      justifyContent: "center",
      gap: "3px",
      padding: "7px 2px",
      borderRadius: "13px",
      border: "none",
      background: "transparent",
      color: T.sub,
      fontSize: "10.5px",
      fontWeight: 600,
      transition: "transform 0.12s ease, background 0.15s ease, color 0.15s ease",
    },
    bottomNavBtnActive: {
      color: dark ? "#E9CF98" : "#FFE2A3",
      background: dark ? "rgba(192,138,62,0.16)" : "rgba(217,163,84,0.30)",
    },
    navIcon: { fontSize: "19px", lineHeight: 1 },
    main: { padding: "0 16px", maxWidth: "560px", margin: "0 auto" },
    // Transparent panel, blurred only in light theme (the default) — clear
    // glass either way, no tint. On-photo text (T.text) is light in both
    // themes since the blurred photo is still dark either way.
    card: {
      background: T.cardBg,
      backdropFilter: dark ? "none" : "blur(20px) saturate(160%)",
      WebkitBackdropFilter: dark ? "none" : "blur(20px) saturate(160%)",
      border: `1px solid ${T.cardBorder}`,
      borderRadius: "18px",
      padding: "18px",
      marginBottom: "16px",
    },
    // Same as card, just a stronger blur — wraps the live-match and
    // tie-break cards.
    cardFrosted: {
      background: T.cardBg,
      backdropFilter: dark ? "none" : "blur(28px) saturate(180%)",
      WebkitBackdropFilter: dark ? "none" : "blur(28px) saturate(180%)",
      border: `1px solid ${T.cardBorder}`,
      borderRadius: "18px",
      padding: "18px",
      marginBottom: "16px",
    },
    h2: { fontFamily: "'Fraunces', serif", fontSize: "17px", fontWeight: 600, margin: "0 0 12px", color: dark ? "#D6B97F" : "#F6D48A", borderLeft: `3px solid ${COLORS.brass}`, paddingLeft: "10px" },
    addRow: { display: "flex", gap: "8px" },
    input: { flex: 1, padding: "10px 12px", borderRadius: "8px", border: `1px solid ${T.inputBorder}`, fontSize: "14px", background: T.inputBg, color: T.solidText },
    brassBtn: { padding: "10px 16px", borderRadius: "8px", border: "none", background: COLORS.brass, color: "#2C1D08", fontWeight: 700, fontSize: "13px" },
    errorText: { color: "#E08877", fontSize: "12.5px", marginTop: "8px" },
    emptyText: { color: T.sub, fontSize: "13.5px", fontStyle: "italic" },
    chipRow: { display: "flex", flexWrap: "wrap", gap: "8px", marginTop: "12px" },
    playerChip: {
      display: "inline-flex",
      alignItems: "center",
      gap: "6px",
      padding: "6px 6px 6px 12px",
      borderRadius: "999px",
      background: T.cardBg,
      backdropFilter: dark ? "none" : "blur(20px) saturate(160%)",
      WebkitBackdropFilter: dark ? "none" : "blur(20px) saturate(160%)",
      border: `1px solid ${T.chipBorder}`,
      fontSize: "13.5px",
      fontWeight: 500,
      color: T.text,
    },
    chipRemove: { border: "none", background: "transparent", color: T.sub, fontSize: "16px", lineHeight: 1, width: "20px", height: "20px", borderRadius: "50%" },
    hint: { fontSize: "12.5px", color: T.sub, margin: "4px 0 0" },
    pickLabel: { fontSize: "14px", fontWeight: 600, color: T.text, margin: "4px 0 0" },
    // Same as hint, but for text inside modals (solid/opaque surfaces —
    // see T.solidSub for why it needs a different color there).
    modalHint: { fontSize: "12.5px", color: T.solidSub, margin: "4px 0 0" },
    selectChip: {
      padding: "8px 14px",
      borderRadius: "999px",
      border: `1.5px solid ${T.pickBorder}`,
      background: T.cardBg,
      backdropFilter: dark ? "none" : "blur(20px) saturate(160%)",
      WebkitBackdropFilter: dark ? "none" : "blur(20px) saturate(160%)",
      color: T.pickText,
      fontWeight: 600,
      fontSize: "13px",
    },
    selectChipActive: { background: T.pickActiveBg, borderColor: T.pickActiveBg, color: T.pickActiveText },
    diceSection: { marginTop: "16px", paddingTop: "14px", borderTop: `1px dashed ${T.chipBorder}` },
    diceBtn: {
      padding: "9px 14px",
      borderRadius: "8px",
      border: `1.5px solid ${T.pickBorder}`,
      background: T.cardBg,
      backdropFilter: dark ? "none" : "blur(20px) saturate(160%)",
      WebkitBackdropFilter: dark ? "none" : "blur(20px) saturate(160%)",
      color: T.pickText,
      fontWeight: 700,
      fontSize: "12.5px",
    },
    // Outline button on the opaque modal card (pale in light theme).
    diceBtnSolid: {
      padding: "9px 14px",
      borderRadius: "8px",
      border: `1.5px solid ${COLORS.chalk}`,
      background: "transparent",
      color: dark ? "#9CC3DE" : COLORS.chalk,
      fontWeight: 700,
      fontSize: "12.5px",
    },
    ghostBtn: { padding: "7px 10px", borderRadius: "8px", border: "1px solid transparent", background: "transparent", color: T.sub, fontWeight: 600, fontSize: "12px" },
    diceRow: { display: "flex", flexWrap: "wrap", gap: "14px", marginTop: "14px" },
    diceCard: { display: "flex", flexDirection: "column", alignItems: "center", gap: "2px" },
    diceFace: { fontSize: "32px", lineHeight: 1, color: dark ? "#D6B97F" : "#F6D48A" },
    diceName: { fontSize: "11px", color: T.sub, fontWeight: 500 },
    tieNote: { marginTop: "10px" },
    breakerBanner: {
      marginTop: "12px",
      padding: "10px 12px",
      borderRadius: "10px",
      background: T.cardBg,
      backdropFilter: dark ? "none" : "blur(20px) saturate(160%)",
      WebkitBackdropFilter: dark ? "none" : "blur(20px) saturate(160%)",
      border: `1px solid ${dark ? "rgba(231,206,147,0.35)" : "#E7CE93"}`,
      color: T.text,
      fontSize: "13px",
      textAlign: "center",
    },
    achievementBanner: {
      marginTop: "12px",
      padding: "10px 12px",
      borderRadius: "10px",
      display: "flex",
      flexDirection: "column",
      gap: "6px",
      background: "linear-gradient(135deg, rgba(217,163,84,0.28) 0%, rgba(169,112,31,0.14) 100%)",
      border: "1px solid rgba(248,225,168,0.6)",
      boxShadow: "0 6px 18px rgba(0,0,0,0.22)",
      textAlign: "left",
    },
    achievementRow: { display: "flex", alignItems: "center", gap: "8px", fontSize: "13px", color: "#FBF3DE" },
    liveHeader: { display: "flex", alignItems: "center", gap: "8px", marginBottom: "4px" },
    liveDot: { width: "9px", height: "9px", borderRadius: "50%", background: "#3E9B5C" },
    scoreboard: { display: "flex", flexDirection: "column", gap: "10px", marginTop: "14px" },
    scoreCard: {
      display: "flex",
      alignItems: "center",
      justifyContent: "space-between",
      padding: "12px 14px",
      borderRadius: "12px",
      background: T.cardBg,
      backdropFilter: dark ? "none" : "blur(22px) saturate(160%)",
      WebkitBackdropFilter: dark ? "none" : "blur(22px) saturate(160%)",
      border: `1px solid ${dark ? "rgba(255,255,255,0.10)" : T.cardBorder}`,
    },
    scoreName: { color: T.text, fontWeight: 600, fontSize: "14px", flex: 1 },
    scoreValue: { fontFamily: "'Space Mono', monospace", fontSize: "22px", fontWeight: 700, color: COLORS.brass, minWidth: "38px", textAlign: "center" },
    scoreInput: {
      fontFamily: "'Space Mono', monospace",
      fontSize: "20px",
      fontWeight: 700,
      color: COLORS.brass,
      background: "rgba(255,255,255,0.06)",
      border: "1px solid #4A6B57",
      borderRadius: "8px",
      width: "56px",
      textAlign: "center",
      padding: "6px 2px",
      cursor: "pointer",
    },
    scoreBtns: { display: "flex", gap: "6px" },
    scoreBtnMinus: { width: "34px", height: "34px", borderRadius: "8px", border: "1px solid #4A6B57", background: "transparent", color: COLORS.cream, fontSize: "16px", touchAction: "manipulation" },
    scoreBtnPlus: { padding: "0 12px", height: "34px", borderRadius: "8px", border: "none", background: COLORS.brass, color: "#2C1D08", fontWeight: 700, fontSize: "12.5px", touchAction: "manipulation" },
    gameActions: { display: "flex", gap: "10px", marginTop: "16px" },
    finishBtn: { flex: 1, padding: "12px", borderRadius: "10px", border: `1.5px solid ${COLORS.felt}`, background: COLORS.felt, color: COLORS.cream, fontWeight: 700, fontSize: "13px" },
    cancelBtn: { flex: 1, padding: "12px", borderRadius: "10px", border: `1.5px solid ${COLORS.danger}`, background: "transparent", color: COLORS.danger, fontWeight: 600, fontSize: "13px" },
    winBtn: { padding: "10px 16px", borderRadius: "10px", border: `1.5px solid ${COLORS.felt}`, background: COLORS.felt, color: COLORS.cream, fontWeight: 700, fontSize: "13px" },
    fsOverlay: {
      background: "radial-gradient(140% 100% at 50% 0%, #16352A 0%, #0A1A14 60%)",
      display: "flex",
      flexDirection: "column",
      paddingTop: "env(safe-area-inset-top)",
      paddingBottom: "env(safe-area-inset-bottom)",
    },
    fsTopBar: { display: "flex", alignItems: "center", gap: "8px", padding: "10px 12px", borderBottom: "1px solid rgba(255,255,255,0.12)" },
    fsTopBtn: {
      padding: "8px 12px",
      borderRadius: "8px",
      border: "1px solid rgba(255,255,255,0.28)",
      background: "rgba(0,0,0,0.2)",
      color: "#F3EBDA",
      fontSize: "12px",
      fontWeight: 700,
    },
    fsBallPicker: { display: "grid", gridTemplateColumns: "repeat(5, 1fr)", gap: "6px", padding: "10px 12px 0" },
    fsBallChip: {
      borderRadius: "10px",
      padding: "9px 0",
      textAlign: "center",
      fontSize: "13px",
      fontWeight: 700,
      border: "1px solid rgba(255,255,255,0.22)",
      background: "rgba(0,0,0,0.22)",
      color: "#F3EBDA",
    },
    fsBallChipActive: { background: COLORS.brass, borderColor: COLORS.brass, color: "#2C1D08" },
    fsReachedBanner: {
      margin: "10px 12px 0",
      padding: "10px 12px",
      borderRadius: "10px",
      background: "rgba(62,155,92,0.2)",
      border: "1px solid #3E9B5C",
      color: "#F3EBDA",
      textAlign: "center",
      fontSize: "13px",
    },
    fsZones: { flex: 1, display: "flex", flexDirection: "row", gap: "2px", minHeight: 0 },
    fsZone: {
      flex: 1,
      display: "flex",
      flexDirection: "column",
      position: "relative",
      cursor: "pointer",
      userSelect: "none",
      touchAction: "manipulation",
      WebkitTapHighlightColor: "transparent",
      minHeight: 0,
    },
    fsZoneCenter: {
      flex: 1,
      minHeight: 0,
      display: "flex",
      flexDirection: "column",
      alignItems: "center",
      justifyContent: "center",
      gap: "10px",
      width: "100%",
    },
    fsZoneName: {
      fontSize: "16px",
      fontWeight: 700,
      color: "#F8F1DE",
      display: "flex",
      alignItems: "center",
      gap: "8px",
      textShadow: "0 2px 6px rgba(0,0,0,0.35)",
      textAlign: "center",
    },
    fsZoneScoreWrap: { display: "inline-block" },
    fsZoneScore: {
      fontFamily: "'Space Mono', monospace",
      fontSize: "min(26vw, 108px)",
      minWidth: "2ch",
      textAlign: "center",
      fontWeight: 700,
      color: "#FBEFD2",
      background: "transparent",
      border: "none",
      lineHeight: 1,
      padding: 0,
      textShadow: "0 3px 8px rgba(0,0,0,0.45)",
    },
    fsZoneMinusBar: {
      width: "100%",
      minHeight: "68px",
      padding: "20px 0",
      border: "none",
      borderTop: "2px solid rgba(224,120,104,0.7)",
      background: "rgba(150,45,35,0.42)",
      color: "#FFE3DC",
      fontSize: "18px",
      fontWeight: 800,
      letterSpacing: "0.3px",
      touchAction: "manipulation",
      WebkitTapHighlightColor: "transparent",
    },
    fsZoneEdit: {
      position: "absolute",
      top: "10px",
      left: "14px",
      width: "38px",
      height: "38px",
      borderRadius: "50%",
      border: "1px solid rgba(255,255,255,0.3)",
      background: "rgba(0,0,0,0.28)",
      color: "#F3EBDA",
      fontSize: "15px",
    },
    fsHint: { textAlign: "center", fontSize: "11.5px", color: "rgba(243,235,218,0.6)", padding: "8px 14px" },
    table: { width: "100%", borderCollapse: "collapse" },
    th: { textAlign: "left", fontSize: "10.5px", textTransform: "uppercase", letterSpacing: "0.04em", color: T.sub, borderBottom: `2px solid ${T.tableBorder}`, padding: "6px 6px" },
    td: { padding: "9px 6px", borderBottom: `1px solid ${T.rowBorder}`, fontSize: "13px", color: T.text },
    mono: { fontFamily: "'Space Mono', monospace" },
    leaderRow: { background: dark ? "rgba(192,138,62,0.12)" : "#FBF0D6" },
    historyList: { listStyle: "none", margin: 0, padding: 0, display: "flex", flexDirection: "column", gap: "2px" },
    historyItem: { display: "flex", justifyContent: "space-between", alignItems: "center", padding: "12px 4px", borderBottom: `1px solid ${T.rowBorder}`, cursor: "pointer" },
    historyPlayers: { fontSize: "13.5px", fontWeight: 500, color: T.text },
    winnerName: { color: dark ? "#8FD3A8" : COLORS.felt, fontWeight: 700 },
    historyDate: { fontFamily: "'Space Mono', monospace", fontSize: "11px", color: T.sub, marginTop: "2px" },
    deleteBtn: { border: "none", background: "transparent", color: "#B08F5A", fontSize: "18px", padding: "4px 8px" },
    resetBtn: { display: "block", width: "100%", padding: "10px 18px", borderRadius: "8px", border: "1px solid #B5473A", background: "transparent", color: "#B5473A", fontSize: "13px", fontWeight: 600 },
    searchRow: { display: "flex", flexWrap: "wrap", gap: "8px", alignItems: "center", marginBottom: "10px" },
    rankList: { listStyle: "none", margin: 0, padding: 0, display: "flex", flexDirection: "column", gap: "8px" },
    rankItem: { display: "flex", alignItems: "center", gap: "10px", padding: "8px 4px", borderBottom: `1px solid ${T.rowBorder}` },
    rankMedal: { width: "26px", textAlign: "center", fontSize: "15px" },
    rankName: { flex: 1, fontSize: "14px", fontWeight: 600, color: T.text },
    rankScore: { fontSize: "12.5px", color: T.sub, fontFamily: "'Space Mono', monospace" },
    settingRow: { display: "flex", justifyContent: "space-between", alignItems: "center", fontSize: "14px", color: T.text },
    settingBtnRow: { display: "flex", gap: "10px", marginTop: "10px", flexWrap: "wrap" },
    switchTrack: { width: "46px", height: "26px", borderRadius: "999px", border: "none", background: "#8A7E63", position: "relative", padding: 0 },
    switchTrackOn: { background: COLORS.brass },
    switchThumb: { position: "absolute", top: "3px", left: "3px", width: "20px", height: "20px", borderRadius: "50%", background: "#fff", transition: "left 0.15s" },
    switchThumbOn: { left: "23px" },
    modalOverlay: { position: "fixed", inset: 0, background: "rgba(0,0,0,0.55)", display: "flex", alignItems: "center", justifyContent: "center", padding: "20px", zIndex: 50 },
    modalCard: { background: T.modalBg, borderRadius: "16px", padding: "20px", maxWidth: "400px", width: "100%", maxHeight: "80vh", overflowY: "auto", boxShadow: "0 10px 30px rgba(0,0,0,0.4)", color: T.solidText },
    modalScores: { display: "flex", flexDirection: "column", gap: "6px", margin: "12px 0" },
    modalRow: { display: "flex", justifyContent: "space-between", fontSize: "14px", padding: "6px 0", borderBottom: `1px solid ${T.rowBorder}`, color: T.solidText },
  };
}
